# MySQL. Versions 5.1.10 and up are supported.
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  collection: utf8mb4_bin
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

production:
  <<: *default
  host: ec2-174-129-209-212.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  username: rnlhwrxgsjgnhg
  password: 592de9761216639ba84c5ca3ee9260778f4c627b2534b95b5ac3acff3a4cb59e
  database: dfpi113gj1oc4f
  post: 5432
